### ISSUE TITLE
Na fase de Reduce, agrupamento dos resultados dos arquivos distribuídos, aconteceu um erro ao calcular a média do tamanho das palavras.

### ISSUE THREAD

**Issue by armandossrecife** [topicos-sistemas-distribuidos/words#1]
```
root@hadoop-master:~/words# ./my-wordaverage.sh -average2
My wordaverage - Try -average2
19/05/28 01:51:14 INFO client.RMProxy: Connecting to ResourceManager at hadoop-master/172.20.0.2:8032
19/05/28 01:51:15 INFO input.FileInputFormat: Total input paths to process : 2
19/05/28 01:51:15 INFO mapreduce.JobSubmitter: number of splits:2
19/05/28 01:51:16 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1558983224769_0004
19/05/28 01:51:16 INFO impl.YarnClientImpl: Submitted application application_1558983224769_0004
19/05/28 01:51:16 INFO mapreduce.Job: The url to track the job: http://hadoop-master:8088/proxy/application_1558983224769_0004/
19/05/28 01:51:16 INFO mapreduce.Job: Running job: job_1558983224769_0004
19/05/28 01:51:28 INFO mapreduce.Job: Job job_1558983224769_0004 running in uber mode : false
19/05/28 01:51:28 INFO mapreduce.Job:  map 0% reduce 0%
19/05/28 01:51:38 INFO mapreduce.Job: Task Id : attempt_1558983224769_0004_m_000001_0, Status : FAILED
Error: java.io.IOException: Type mismatch in value from map: expected org.apache.hadoop.io.Text, received org.apache.hadoop.io.IntWritable
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1077)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:715)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:32)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:19)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

19/05/28 01:51:39 INFO mapreduce.Job:  map 50% reduce 0%
19/05/28 01:51:39 INFO mapreduce.Job: Task Id : attempt_1558983224769_0004_m_000000_0, Status : FAILED
Error: java.io.IOException: Type mismatch in value from map: expected org.apache.hadoop.io.Text, received org.apache.hadoop.io.IntWritable
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1077)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:715)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:32)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:19)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

19/05/28 01:51:40 INFO mapreduce.Job:  map 0% reduce 0%
19/05/28 01:51:49 INFO mapreduce.Job: Task Id : attempt_1558983224769_0004_m_000001_1, Status : FAILED
Error: java.io.IOException: Type mismatch in value from map: expected org.apache.hadoop.io.Text, received org.apache.hadoop.io.IntWritable
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1077)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:715)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:32)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:19)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

19/05/28 01:51:50 INFO mapreduce.Job: Task Id : attempt_1558983224769_0004_m_000000_1, Status : FAILED
Error: java.io.IOException: Type mismatch in value from map: expected org.apache.hadoop.io.Text, received org.apache.hadoop.io.IntWritable
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1077)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:715)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:32)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:19)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

19/05/28 01:51:58 INFO mapreduce.Job: Task Id : attempt_1558983224769_0004_m_000000_2, Status : FAILED
Error: java.io.IOException: Type mismatch in value from map: expected org.apache.hadoop.io.Text, received org.apache.hadoop.io.IntWritable
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1077)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:715)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:32)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:19)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

19/05/28 01:51:58 INFO mapreduce.Job: Task Id : attempt_1558983224769_0004_m_000001_2, Status : FAILED
Error: java.io.IOException: Type mismatch in value from map: expected org.apache.hadoop.io.Text, received org.apache.hadoop.io.IntWritable
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1077)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:715)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:32)
	at br.ufc.great.es.tsd.mapreduce.words.WordAverage$TokenizerAverageMapper.map(WordAverage.java:19)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

19/05/28 01:52:07 INFO mapreduce.Job:  map 100% reduce 100%
19/05/28 01:52:07 INFO mapreduce.Job: Job job_1558983224769_0004 failed with state FAILED due to: Task failed task_1558983224769_0004_m_000000
Job failed as tasks failed. failedMaps:1 failedReduces:0

19/05/28 01:52:07 INFO mapreduce.Job: Counters: 17
	Job Counters 
		Failed map tasks=7
		Killed map tasks=1
		Killed reduce tasks=1
		Launched map tasks=8
		Other local map tasks=6
		Data-local map tasks=2
		Total time spent by all maps in occupied slots (ms)=62287
		Total time spent by all reduces in occupied slots (ms)=0
		Total time spent by all map tasks (ms)=62287
		Total time spent by all reduce tasks (ms)=0
		Total vcore-milliseconds taken by all map tasks=62287
		Total vcore-milliseconds taken by all reduce tasks=0
		Total megabyte-milliseconds taken by all map tasks=63781888
		Total megabyte-milliseconds taken by all reduce tasks=0
	Map-Reduce Framework
		CPU time spent (ms)=0
		Physical memory (bytes) snapshot=0
		Virtual memory (bytes) snapshot=0

input file1.txt:
Hello Hadoop

input file2.txt:
Hello Docker

wordaverage output:
cat: `output-average2/part-r-00000': No such file or directory
```

**Comment by armandossrecife** [comment]
O erro foi corrigido, pois estava faltando fazer mais uma classe de reduce para calcular a média do tamanho de cada fragmento de reduce.
